config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'
  resources :courses, only: :index do
    resources :groups, only: :index
  end

  resources :groups, only: :show do
    resources :registrations, only: :create
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  acts_as_paranoid

  validates :name, presence: true
  validates :name, uniqueness: true

  has_many :groups, dependent: :destroy

  accepts_nested_attributes_for :groups, allow_destroy: true

  scope :sorted_by_starts_at,
        lambda {
          groups = Group.arel_table
          groups_join = arel_table.join(groups, Arel::Nodes::OuterJoin)
                                  .on(
                                    arel_table[:id]
                                      .eq(groups[:course_id])
                                      .and(groups[:starts_at].gt(Time.current))
                                  ).join_sources
          joins(groups_join).group(:id).order('MIN(groups.starts_at)')
        }
end

app/models/group.rb
class Group < ApplicationRecord
  acts_as_paranoid

  belongs_to :course

  has_many :registrations, dependent: :destroy

  scope :after_now, -> { where('starts_at > ?', Time.current) }

  def in_the_future?
    starts_at > Time.current
  end
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :group

  validates :email, format: { with: /\A[^@]+@[^\.]+\..+\z/ }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :render_not_found

  private

  def render_not_found
    render json: { errors: ['Not found'] }, status: :not_found
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.includes(groups: :registrations)
    if params[:order_by] == 'starts_at'
      @courses = @courses.sorted_by_starts_at
      @ordered = true
    end
    @courses = @courses.all.decorate
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.after_now
                   .includes(:registrations)
                   .where(course_id: params[:course_id]).decorate
  end

  def show
    @group = Group.find(params[:id]).decorate
    @course = @group.course.decorate
    @registrations = @group.registrations.decorate
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def create
    if registration_result[:errors].blank?
      head :created
    else
      render json: { errors: registration_result[:errors] },
             status: :unprocessable_entity
    end
  end

  private

  def registration_result
    @registration_result ||=
      Registrar.new(email: params.require(:registration)[:email],
                    group: Group.after_now.find(params[:group_id])).call
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/index.html.haml
%table(border="2")
  %thead
    %tr
      %th(colspan="4")= t('.courses')
    %tr
      %th= t('.name')
      %th
        = link_to(t('.starts_at'),
                  root_path(@ordered ? {} : { order_by: :starts_at }))
      %th= t('.registrations')
      %th
  - @courses.each do |course|
    %tr
      %td= course.name
      %td= course.starts_at
      %td= course.registrations_count
      %td
        = link_to(t('.groups'), course_groups_path(course_id: course.id))

app/views/groups/index.html.haml
= link_to(t('.back'), root_path)

%table(border="2")
  %thead
    %tr
      %th(colspan="4")= t('.groups')
    %tr
      %th= t('.starts_at')
      %th= t('.registrations_count')
      %th
      %th

  - @groups.each do |group|
    %tr
      %td= group.starts_at
      %td= group.registrations_count
      %td= link_to(t('.show_group'), group_path(group))
      %td= render partial: 'registrations/new', locals: { group_id: group.id }

app/views/groups/show.html.haml
= link_to(t('.back'), course_groups_path(course_id: @group.course_id))
%table(border="2")
  %thead
    %tr
      %th(colspan="3")
        = t('.course')
        = @group.course.name
        = t('.group_starts_at')
        = @group.starts_at
    %tr
      %th= t('.email')
  - @registrations.each do |registration|
    %tr
      %td= registration.email

  %tr
    %td= render partial: 'registrations/new', locals: { group_id: @group.id }

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title LectureHall
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield